### ISSUE TITLE
Start TimeProfileBrowser in menu

### ISSUE THREAD

**Issue by simsieg** [HPI-SWA-Teaching/SWT17-Project-05#16]
I as developer want to be able to start the TimeProfileBrowser from the menu.
It should should spy on everything that happens like the Profiler.

**Comment by jkbe** [comment]
First do it generic: Spy on everything that happens.
(Later maybe: Include launcher that lets user specify a Block to spy on.)

**Comment by jkbe** [comment]
Look at startMessageTally

**Comment by jkbe** [comment]
Completed both subtasks. Later on, we might want to add more options to the "Launcher" than just providing a block that the TimeProfileBrowser should spy on.

**Comment by jkbe** [comment]
Done and accepted.
