### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by dominikglandorf** [HPI-SWA-Teaching/SWT17-Project-05#3]
As a developer, I want to use the keyboard to start the analysis.

**Comment by jkbe** [comment]
Good user story.
How to inform about what shortcuts are available?
- set them in Tools -> Preferences?
- How to implement? Who listens to keyboard events? Usually Window/Morph --> find global KeyHandler
- How to trigger this behavior and what to expect?

**Comment by jak-ing** [comment]
How to trigger this behavior?

**Comment by jkbe** [comment]
Start the program == Start the analysis

**Comment by jchromik** [comment]
Please also implement the following:

- [x] Shortcuts should appear in menu bar as hint ((New)BalloonMorph maybe)
- [x] Shortcuts should work on all OS (in the same way -ish)

**Comment by jchromik** [comment]
Shortcut hints should reflect the actual shortcut (different hints on different os's).
