### ISSUE TITLE
Collapse Node

### ISSUE THREAD

**Issue by jkbe** [HPI-SWA-Teaching/SWT17-Project-05#5]
As a user, I want to have the possibility to click on a small arrow in front of every node, to hide / "collapse" all child nodes. As a result, I can blackbox some function calls whose measured values are not relevant to me so that I gain a better overview of processing times on a higher level.

**Comment by jkbe** [comment]
PluggableTreeMorph as used in the Object Explorer (ctrl + shift + i when an object is selected/highlighted) looks promising.

**Comment by jkbe** [comment]
<img width="443" alt="screen shot 2017-05-22 at 11 06 56" src="https://cloud.githubusercontent.com/assets/15202881/26300903/c4caf898-3edf-11e7-8d97-83d181fa06b7.png">

**Comment by flowirtz** [comment]
Split user story into 2:
- print to custom data format
- create tree from message tally data from 1
in 2 pair programming teams of each 2 people.

Expected to be done next week (8 coffee mugs...)

**Comment by jkbe** [comment]
With 77a0d7c, a hard-coded tree is displayed in the result window of the TimeProfileBrowser.

**Comment by MariusDanner** [comment]
made new branch issue-5_1 that lets the TallyTree be the model

**Comment by jkbe** [comment]
Done.
