### ISSUE TITLE
Preview Method Code

### ISSUE THREAD

**Issue by dominikglandorf** [HPI-SWA-Teaching/SWT17-Project-05#8]
Ich möchte als Entwickler die aufgerufenen Funktionen über einen Klick oder Tastendruck erreichen können.

**Comment by jkbe** [comment]
This is already possible when using TimeProfileBrowser if I'm getting you right.

**Comment by simsieg** [comment]
Global KeyHandler is needed

**Comment by jkbe** [comment]
Done with #5
